trigger:
- master

pool:
  vmImage: "Ubuntu-16.04"

steps:
- task: NodeTool@0
  inputs:
    versionSpec: "8.x"
  displayName: "Install Node.js"

- script: yarn install --frozen-lockfile
  displayName: "Install dependencies"

- script: yarn format:ci
  displayName: "Format source with Prettier"

- script: yarn lint
  displayName: "Lint source with ESLint"

- script: yarn test
  displayName: "Run tests with Jest"

- script: yarn build
  displayName: "Build with Rollup"

- task: PublishTestResults@2
  inputs:
    testResultsFiles: "*/junit.xml"
    testRunTitle: "Jest"
  displayName: "Publish test results"

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: "Cobertura"
    reportDirectory: "$(System.DefaultWorkingDirectory)/coverage"
    summaryFileLocation: "$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml"
  displayName: "Publish code coverage"
