---
# configuration
env:
  browser: true
  es6: true
parser: "babel-eslint"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: "module"
plugins:
- "react"
settings:
  react:
    pragma: "createElement"
    version: "16.7.0-alpha.2"

# rules
rules:

  # possible errors
  for-direction:
  - 2
  getter-return:
  - 2
  no-async-promise-executor:
  - 2
  no-await-in-loop:
  - 0
  no-compare-neg-zero:
  - 2
  no-cond-assign:
  - 2
  - "always"
  no-console:
  - 2
  no-constant-condition:
  - 2
  - checkLoops: false
  no-control-regex:
  - 2
  no-debugger:
  - 2
  no-dupe-args:
  - 2
  no-dupe-keys:
  - 2
  no-duplicate-case:
  - 2
  no-empty:
  - 2
  no-empty-character-class:
  - 2
  no-ex-assign:
  - 2
  no-extra-boolean-cast:
  - 2
  no-extra-parens:
  - 0
  no-extra-semi:
  - 2
  no-func-assign:
  - 2
  no-inner-declarations:
  - 2
  - "both"
  no-invalid-regexp:
  - 0
  no-irregular-whitespace:
  - 2
  - skipStrings: false
  no-obj-calls:
  - 2
  no-prototype-builtins:
  - 2
  no-regex-spaces:
  - 2
  no-sparse-arrays:
  - 2
  no-unexpected-multiline:
  - 2
  no-unreachable:
  - 2
  no-unsafe-finally:
  - 2
  no-unsafe-negation:
  - 2
  require-atomic-updates:
  - 0
  use-isnan:
  - 2
  valid-typeof:
  - 2
  - requireStringLiterals: true

  # best practices
  accessor-pairs:
  - 0
  array-callback-return:
  - 0
  block-scoped-var:
  - 2
  class-methods-use-this:
  - 2
  complexity:
  - 0
  consistent-return:
  - 0
  curly:
  - 0
  default-case:
  - 2
  - commentPattern: "$^"
  dot-location:
  - 2
  - "property"
  dot-notation:
  - 2
  eqeqeq:
  - 2
  - "always"
  - null: "ignore"
  guard-for-in:
  - 2
  max-classes-per-file:
  - 2
  - 1
  no-alert:
  - 2
  no-caller:
  - 2
  no-case-declarations:
  - 2
  no-div-regex:
  - 0
  no-else-return:
  - 2
  - allowElseIf: true
  no-empty-function:
  - 0
  no-empty-pattern:
  - 2
  no-eq-null:
  - 0
  no-eval:
  - 2
  no-extend-native:
  - 2
  no-extra-bind:
  - 2
  no-extra-label:
  - 0
  no-fallthrough:
  - 2
  no-floating-decimal:
  - 2
  no-global-assign:
  - 2
  no-implicit-coercion:
  - 0
  no-implicit-globals:
  - 0
  no-implied-eval:
  - 2
  no-invalid-this:
  - 0
  no-iterator:
  - 2
  no-labels:
  - 2
  no-lone-blocks:
  - 2
  no-loop-func:
  - 2
  no-magic-numbers:
  - 0
  no-multi-spaces:
  - 2
  - exceptions:
      Property: false
    ignoreEOLComments: true
  no-multi-str:
  - 2
  no-new:
  - 2
  no-new-func:
  - 2
  no-new-wrappers:
  - 2
  no-octal:
  - 2
  no-octal-escape:
  - 2
  no-param-reassign:
  - 2
  - props: false
  no-proto:
  - 2
  no-redeclare:
  - 2
  no-restricted-properties:
  - 0
  no-return-assign:
  - 2
  - "always"
  no-return-await:
  - 2
  no-script-url:
  - 2
  no-self-assign:
  - 2
  no-self-compare:
  - 2
  no-sequences:
  - 2
  no-throw-literal:
  - 2
  no-unmodified-loop-condition:
  - 2
  no-unused-expressions:
  - 2
  no-unused-labels:
  - 0
  no-useless-call:
  - 0
  no-useless-catch:
  - 2
  no-useless-concat:
  - 2
  no-useless-escape:
  - 2
  no-useless-return:
  - 2
  no-void:
  - 0
  no-warning-comments:
  - 0
  no-with:
  - 2
  prefer-promise-reject-errors:
  - 2
  radix:
  - 2
  - "as-needed"
  require-await:
  - 0
  require-unicode-regexp:
  - 0
  vars-on-top:
  - 2
  wrap-iife:
  - 0
  yoda:
  - 2
  - "never"

  # strict mode
  strict:
  - 0

  # variables
  init-declarations:
  - 0
  no-delete-var:
  - 2
  no-label-var:
  - 2
  no-restricted-globals:
  - 0
  no-shadow:
  - 0
  no-shadow-restricted-names:
  - 2
  no-undef:
  - 2
  no-undef-init:
  - 2
  no-undefined:
  - 2
  no-unused-vars:
  - 2
  no-use-before-define:
  - 0
  # stylistic issues
  array-bracket-newline:
  - 2
  - "consistent"
  array-bracket-spacing:
  - 2
  - "never"
  array-element-newline:
  - 2
  - "consistent"
  block-spacing:
  - 2
  - "always"
  brace-style:
  - 2
  - "1tbs"
  camelcase:
  - 2
  - ignoreDestructuring: false
    properties: "always"
  capitalized-comments:
  - 0
  comma-dangle:
  - 2
  - "always-multiline"
  comma-spacing:
  - 2
  - after: true
    before: false
  comma-style:
  - 2
  - "last"
  computed-property-spacing:
  - 2
  - "never"
  consistent-this:
  - 0
  eol-last:
  - 2
  - "always"
  func-call-spacing:
  - 2
  - "never"
  func-name-matching:
  - 0
  func-names:
  - 2
  - "as-needed"
  func-style:
  - 2
  - "expression"
  function-paren-newline:
  - 0
  id-blacklist:
  - 0
  id-length:
  - 2
  - min: 3
  id-match:
  - 0
  implicit-arrow-linebreak:
  - 0
  indent:
  - 0
  jsx-quotes:
  - 2
  - "prefer-double"
  key-spacing:
  - 0
  keyword-spacing:
  - 2
  - after: true
    before: true
  line-comment-position:
  - 0
  linebreak-style:
  - 2
  - "unix"
  lines-around-comment:
  - 0
  lines-between-class-members:
  - 2
  - "always"
  max-depth:
  - 2
  - max: 2
  max-len:
  - 0
  max-lines:
  - 0
  max-lines-per-function:
  - 0
  max-nested-callbacks:
  - 0
  max-params:
  - 2
  - max: 3
  max-statements:
  - 0
  max-statements-per-line:
  - 0
  - max: 1
  multiline-comment-style:
  - 2
  - "separate-lines"
  multiline-ternary:
  - 0
  new-cap:
  - 2
  - capIsNew: false
    newIsCap: true
    properties: true
  new-parens:
  - 2
  newline-per-chained-call:
  - 0
  no-array-constructor:
  - 2
  no-bitwise:
  - 0
  no-continue:
  - 2
  no-inline-comments:
  - 0
  no-lonely-if:
  - 2
  no-mixed-operators:
  - 0
  no-mixed-spaces-and-tabs:
  - 2
  no-multi-assign:
  - 2
  no-multiple-empty-lines:
  - 2
  - max: 1
  no-negated-condition:
  - 0
  no-nested-ternary:
  - 0
  no-new-object:
  - 2
  no-plusplus:
  - 0
  no-restricted-syntax:
  - 2
  - "ClassDeclaration"
  - "ClassExpression"
  - "ForInStatement"
  - "FunctionDeclaration[generator=false]"
  - "FunctionExpression[generator=false]"
  - "ThisExpression"
  no-tabs:
  - 2
  no-ternary:
  - 0
  no-trailing-spaces:
  - 2
  no-underscore-dangle:
  - 2
  no-unneeded-ternary:
  - 2
  no-whitespace-before-property:
  - 2
  nonblock-statement-body-position:
  - 2
  - "beside"
  object-curly-newline:
  - 2
  - consistent: true
  object-curly-spacing:
  - 2
  - "always"
  object-property-newline:
  - 0
  one-var:
  - 2
  - initialized: "never"
    uninitialized: "always"
  one-var-declaration-per-line:
  - 2
  - "initializations"
  operator-assignment:
  - 2
  - "always"
  operator-linebreak:
  - 0
  padded-blocks:
  - 2
  - "never"
  padding-line-between-statements:
  - 0
  prefer-object-spread:
  - 2
  quote-props:
  - 2
  - "consistent-as-needed"
  quotes:
  - 2
  - "double"
  semi:
  - 2
  - "never"
  semi-spacing:
  - 2
  - after: true
    before: false
  semi-style:
  - 0
  sort-keys:
  - 2
  - "asc"
  - caseSensitive: true
    natural: true
  sort-vars:
  - 0
  space-before-blocks:
  - 2
  - "always"
  space-before-function-paren:
  - 0
  space-in-parens:
  - 2
  - "never"
  space-infix-ops:
  - 2
  - int32Hint: false
  space-unary-ops:
  - 2
  - nonwords: false
    words: true
  spaced-comment:
  - 2
  - "always"
  switch-colon-spacing:
  - 2
  - after: true
    before: false
  template-tag-spacing:
  - 2
  - "never"
  unicode-bom:
  - 2
  - "never"
  wrap-regex:
  - 0

  # ecmascript 6
  arrow-body-style:
  - 2
  - "as-needed"
  arrow-parens:
  - 2
  - "as-needed"
  arrow-spacing:
  - 2
  - after: true
    before: true
  constructor-super:
  - 2
  generator-star-spacing:
  - 0
  no-class-assign:
  - 2
  no-confusing-arrow:
  - 0
  no-const-assign:
  - 2
  no-dupe-class-members:
  - 2
  no-duplicate-imports:
  - 2
  no-new-symbol:
  - 2
  no-restricted-imports:
  - 0
  no-this-before-super:
  - 2
  no-useless-computed-key:
  - 2
  no-useless-constructor:
  - 2
  no-useless-rename:
  - 2
  no-var:
  - 2
  object-shorthand:
  - 2
  - "always"
  prefer-arrow-callback:
  - 2
  - allowNamedFunctions: false
    allowUnboundThis: false
  prefer-const:
  - 2
  - destructuring: "any"
    ignoreReadBeforeAssign: false
  prefer-destructuring:
  - 2
  - AssignmentExpression:
      array: false
      object: false
    VariableDeclarator:
      array: true
      object: true
  prefer-numeric-literals:
  - 2
  prefer-rest-params:
  - 2
  prefer-spread:
  - 2
  prefer-template:
  - 2
  require-yield:
  - 2
  rest-spread-spacing:
  - 2
  - "never"
  sort-imports:
  - 0
  symbol-description:
  - 0
  template-curly-spacing:
  - 2
  - "never"
  yield-star-spacing:
  - 0
  # react
  react/boolean-prop-naming:
  - 0
  react/button-has-type:
  - 2
  react/default-props-match-prop-types:
  - 0
  react/destructuring-assignment:
  - 0
  react/display-name:
  - 2
  react/forbid-component-props:
  - 0
  react/forbid-dom-props:
  - 0
  react/forbid-elements:
  - 0
  react/forbid-prop-types:
  - 0
  react/forbid-foreign-prop-types:
  - 0
  react/no-access-state-in-setstate:
  - 2
  react/no-array-index-key:
  - 2
  react/no-children-prop:
  - 0
  react/no-danger:
  - 2
  react/no-danger-with-children:
  - 2
  react/no-deprecated:
  - 2
  react/no-did-mount-set-state:
  - 2
  react/no-direct-mutation-state:
  - 2
  react/no-find-dom-node:
  - 2
  react/no-is-mounted:
  - 2
  react/no-multi-comp:
  - 2
  react/no-redundant-should-component-update:
  - 2
  react/no-render-return-value:
  - 2
  react/no-set-state:
  - 0
  react/no-typos:
  - 0
  react/no-string-refs:
  - 2
  react/no-this-in-sfc:
  - 2
  react/no-unescaped-entities:
  - 0
  react/no-unknown-property:
  - 2
  react/no-unsafe:
  - 2
  react/no-unused-prop-types:
  - 0
  react/no-unused-state:
  - 0
  react/no-will-update-set-state:
  - 2
  react/prefer-es6-class:
  - 2
  - "always"
  react/prefer-stateless-function:
  - 0
  react/prop-types:
  - 0
  react/react-in-jsx-scope:
  - 2
  react/require-default-props:
  - 0
  react/require-optimization:
  - 0
  react/require-render-return:
  - 2
  react/self-closing-comp:
  - 2
  react/sort-comp:
  - 0
  react/sort-prop-types:
  - 2
  react/style-prop-object:
  - 2
  react/void-dom-elements-no-children:
  - 2

  # jsx
  react/jsx-boolean-value:
  - 0
  react/jsx-child-element-spacing:
  - 2
  react/jsx-closing-bracket-location:
  - 2
  - "tag-aligned"
  react/jsx-closing-tag-location:
  - 2
  react/jsx-curly-brace-presence:
  - 0
  react/jsx-curly-spacing:
  - 2
  - allowMultiline: false
    when: "never"
  react/jsx-equals-spacing:
  - 2
  - "never"
  react/jsx-filename-extension:
  - 2
  - extensions:
    - ".js"
  react/jsx-first-prop-new-line:
  - 2
  - "multiline"
  react/jsx-handler-names:
  - 2
  - eventHandlerPrefix: "handle"
    eventHandlerPropPrefix: "on"
  react/jsx-indent:
  - 2
  - 2
  react/jsx-indent-props:
  - 2
  - 2
  react/jsx-key:
  - 2
  react/jsx-max-depth:
  - 0
  react/jsx-max-props-per-line:
  - 0
  react/jsx-no-bind:
  - 2
  react/jsx-no-comment-textnodes:
  - 2
  react/jsx-no-duplicate-props:
  - 2
  react/jsx-no-literals:
  - 2
  - noStrings: true
  react/jsx-no-target-blank:
  - 2
  react/jsx-no-undef:
  - 2
  react/jsx-one-expression-per-line:
  - 2
  - allow: "single-child"
  react/jsx-pascal-case:
  - 2
  react/jsx-props-no-multi-spaces:
  - 2
  react/jsx-sort-default-props:
  - 2
  react/jsx-sort-props:
  - 2
  - reservedFirst:
    - "key"
    - "ref"
  react/jsx-tag-spacing:
  - 2
  - afterOpening: "never"
    beforeClosing: "never"
    beforeSelfClosing: "always"
    closingSlash: "never"
  react/jsx-uses-react:
  - 2
  react/jsx-uses-vars:
  - 2
  react/jsx-wrap-multilines:
  - 0

# overrides
overrides:
- files:
  - "*.config.js"
  env:
    browser: false
    es6: true
    node: true
- files:
  - "*.test.js"
  env:
    browser: true
    es6: true
    jest: true
  rules:
    id-length:
    - 0
    react/no-multi-comp:
    - 0
